### PR TITLE
Update .NET 8.0 & packages

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@theo-blis please check while you are working on extracting PO, I just updated to .NET 8

**Comment by theo-blis** [comment]
@hishamco I didn't want to push you to upgrade ;-) I ran the same test and it still produces the same results. So all is good!

**Comment by hishamco** [comment]
Believe it or not when I created the latest fix I thought to remove it and then allow ignored projects as parameters, please file an issue for easy tracking. I know I might forget this if it's not logged :)

**Comment by theo-blis** [comment]
See #83

**Pull request merged**
