### PR TITLE
updated to .net6

### PR DESCRIPTION
**Pull request by brunoAltinet**

### CODE REVIEW

**Comment by Skrypt** [comment]
Who's managing this repository? And can this be merged?

**Comment by rjpowers10** [comment]
@hishamco there's no rush but this is the PR I'm most interested in. If you run `dotnet tool install --global PoExtractor.OrchardCore` it will install version 0.2.0 which requires .NET Core 3.0 to be installed. If you instead install `dotnet tool install --global PoExtractor.OrchardCore --version 0.4.0-rc1-13272` that is a little better because it requires .NET Core 3.1, but even that is about to go out of support in Decemeber.

**Comment by hishamco** [comment]
@rjpowers10 everything is upgraded, hope to push a newer version after few days. FYI I might need to fix few related issues

**Comment by rjpowers10** [comment]
@hishamco Thank you!

**Pull request closed without merging**
