### PR TITLE
Merge extractpo & extractpo-oc into a single one

### LINKED ISSUE #64: Merge PoExtractor & PoExtractor.OrchardCore into a single tool
Now we have two tools which do the same things except `PoExtractor.OrchardCore` extend the first one by supporting liquid, while the intend of `PoExtractor` to extract translatable strings in Orchard Core, single tool is enough. We might extend this tool by having options to skip certain template

/cc @Skrypt

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #64

### CODE REVIEW

**Comment by hishamco** [comment]
@lukaskabrt why there's a red mesage when I created a PR, is this related to some permissions?

**Comment by lukaskabrt** [comment]
@hishamco I don't see any red message, but it seems there is some problem with PR checks. 

It might be possible that moving the project under OrchardCoreContrib broke the integration with Azure DevOps, because I don't see any new builds there. 

I don't see project settings here at GitHub anymore, so I am unable to check it further. Can you access DevOps project at https://dev.azure.com/kabrt/PoExtractor ? I have added you as a project contributor.

**Comment by hishamco** [comment]
> It might be possible that moving the project under OrchardCoreContrib broke the integration with Azure DevOps, because I don't see any new builds there.

I removed teh AzurePipelines checks and using GitHub workflow

 _Merge without waiting for requirements to be met (bypass branch protections)_

This is the message show up above the merge button, I will check the setting again, otherwise I will give you an access to check if you have time

Thanks

**Comment by hishamco** [comment]
There was a rule on the `master` branch, I delete it and everything is fine now ;)

**Pull request merged**
